### ISSUE TITLE
What's the difference of this from `ray-x/lsp_signature.nvim`?

### ISSUE THREAD

**Issue by nyngwang** [mjlbach/lsp_signature.nvim#1]
As title. I'm using [ray-x/lsp_signature](https://github.com/ray-x/lsp_signature.nvim) but it's kinda laggy. This info will be helpful for people using this plugin :) Thank you

**Comment by mjlbach** [comment]
By my count, that plugin is around 1400 loc, this is about 140 (and less, if/when I upstream some modifications to the signature help handler since half of the plugin is a duplicated handler). I don't care if people us lsp_signature.nvim, the name is a coincidence, it was the most obvious name for something that opens signature help for you.

**Comment by nyngwang** [comment]
OK cool. Feel free to tag me if you have some new features that need someone to test.
